stages:
  train_p1:
    foreach: [ effnet_s, effnet_m, convnext ]
    do:
      cmd: python -m src.train --model ${item} --data data/split/train --out models/p1/${item} --batch 16 --epochs 4
      deps:
        - data/split/train
        - src/train.py
        - src/common.py
      outs:
        - models/p1/${item}/model.pth
        - models/p1/${item}/loss_plot.png
        - models/p1/${item}/history.json

  evaluate_p1:
    foreach: [ effnet_s, effnet_m, convnext ]
    do:
      cmd: python -m src.test --model ${item} --data data/split/train --out models/p1/${item} --batch 8
      deps:
        - data/split/test
        - src/test.py
        - src/common.py
        - models/p1/${item}/model.pth
      metrics:
        - models/p1/${item}/metrics.json:
            cache: false
      plots:
        - models/p1/${item}/test_confusion_matrix.png:
            cache: false