stages:
  augment:
    wdir: ..
    cmd: >
      python -m src.augment
      pipeline=pipeline3
    deps:
      - data/split/train
      - src/augment.py
    params:
      - conf/config.yaml:
      - conf/pipeline/pipeline3.yaml:
    outs:
      - pipeline3/data/augmented/train

  stage-1:
    foreach: [ effnet_s, effnet_m, convnext ]
    do:
      wdir: ..
      cmd: >
        python -m src.train 
        pipeline=pipeline3
        model=${item}
      deps:
        - pipeline3/data/augmented/train
        - data/split/val
        - src/train.py
        - src/common.py
      params:
        - conf/config.yaml:
        - conf/pipeline/pipeline3.yaml:
        - conf/model/${item}.yaml:
      outs:
        - pipeline3/${item}/model.pth

  stage-2: # fine-tuning
    foreach: [ effnet_s, effnet_m, convnext ]
    do:
      wdir: ..
      cmd: >
        python -m src.finetune 
        pipeline=pipeline3 
        model=${item}
      deps:
        - pipeline3/data/augmented/train
        - data/split/val
        - src/finetune.py
        - src/common.py
        - pipeline3/${item}/model.pth
      params:
        - conf/config.yaml:
        - conf/pipeline/pipeline3.yaml:
        - conf/model/${item}.yaml:
      outs:
        - pipeline3/${item}/finetuned/model.pth
        - pipeline3/${item}/finetuned/loss.json


  evaluate:
    foreach: [ effnet_s, effnet_m, convnext ]
    do:
      wdir: ..
      cmd: >
        python -m src.evaluate 
        pipeline=pipeline3 
        model=${item}
      deps:
        - data/split/test
        - src/evaluate.py
        - src/common.py
        - pipeline3/${item}/finetuned/model.pth
      params:
        - conf/config.yaml:
        - conf/pipeline/pipeline3.yaml:
        - conf/model/${item}.yaml:
      metrics:
        - pipeline3/${item}/finetuned/metrics.json:
            cache: false
      plots:
        - pipeline3/${item}/finetuned/cm_data.csv:
            template: confusion
            x: actual
            y: predicted
            title: "Pipeline 2 - Two-Stage Fine-Tuning CM - ${item}"
            cache: false

plots:
    - Training_Loss_Comparison:
        template: linear
        x: epoch
        y:
          # Qui confrontiamo le performance di addestramento tra i modelli
          effnet_s/loss.json: train_loss
          effnet_m/loss.json: train_loss
          convnext/loss.json: train_loss
        title: "Pipeline 3 - Comparison: Training Loss per Model"

    - effnet_s_curves:
        template: linear
        x: epoch
        y:
          effnet_s/finetuned/loss.json: [ train_loss, val_loss ]
        title: "Pipeline 3 - EfficientNet S: Train vs Val"

    - effnet_m_curves:
        template: linear
        x: epoch
        y:
          effnet_m/finetuned/loss.json: [ train_loss, val_loss ]
        title: "Pipeline 3 - EfficientNet M: Train vs Val"

    - convnext_curves:
        template: linear
        x: epoch
        y:
          convnext/finetuned/loss.json: [ train_loss, val_loss ]
        title: "Pipeline 3 - ConvNeXt: Train vs Val"