out_dir: experiments/pipeline1/

augment:
  src_dir: data/split
  dst_dir: experiments/pipeline1/data/augmented
  force: False

trainset_path: experiments/pipeline1/data/augmented/train

train:
  lr: 0.001
  epochs: 4
  batch_size: 16

tsft: false