out_dir: experiments/pipeline3/

augment:
  src_dir: data/split
  dst_dir: experiments/pipeline3/data/augmented
  force: False

trainset_path: experiments/pipeline3/data/augmented/train

train:
  lr: 0.001
  epochs: 4
  batch_size: 16

tsft: true

finetuning:
  lr: 0.0001
  epochs: 5
  batch_size: 16