base:
  image_res: 224

data:
  tobalance_path: data/split
  balanced_path: data_balanced/train
  trainset_path: data_balanced/train
  valset_path: data/split/val
  testset_path: data/split/test

train:
  epochs: 4
  batch_size: 16

evaluate:
  batch_size: 16

finetuning:
  data_path: data/split/train
  lr: 0.0001
  epochs: 5
  batch_size: 16