base:
  image_res: 224

data:
  trainset_path: data/split/train
  valset_path: data/split/val
  testset_path: data/split/test

train:
  lr: 0.001
  epochs: 4
  batch_size: 16

evaluate:
  batch_size: 16
